# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    resolvers:
        default:
            web_path: ~
    filter_sets:
        article_thumbnail:
            filters:
                thumbnail: { size: [100, 100], mode: inset }
        article_index:
            filters:
                thumbnail: { size: [300, 200], mode: inset }
        article_page:
            filters:
                thumbnail: { size: [600, 400], mode: inset }
